// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvgSipwjUXLJAytr_RPVOwxR4uydHpY5A',
    appId: '1:447948738768:web:4db78e092076d1d6e48ed5',
    messagingSenderId: '447948738768',
    projectId: 'project-novella-app',
    authDomain: 'project-novella-app.firebaseapp.com',
    storageBucket: 'project-novella-app.firebasestorage.app',
    measurementId: 'G-PRM8RB19DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh0TdZGxoz2tMDhC4ZvzSTi62Krjp7w4U',
    appId: '1:447948738768:android:37bec5f70c8d5673e48ed5',
    messagingSenderId: '447948738768',
    projectId: 'project-novella-app',
    storageBucket: 'project-novella-app.firebasestorage.app',
  );
}
